import { UUID } from 'mongodb';
import { model, models, Schema } from 'mongoose';
import { JournalEntry, Category } from '@/types/journalEntry';

const JournalEntrySchema = new Schema<JournalEntry>(  
    {  
        id: UUID, // @todo should be generated by db
        createdAt: Date, //@todo should be generated by db
        updatedAt: Date, //@todo should be generated by db
        userId: UUID, // @todo what is the best way to get posts for the user
        tittle: String,  
        content: String,  
        category: Category,
        additionalCategory: Category,
    },  
    {  
        timestamps: true, 
    },
);  
const JournalEntry = models.JournalEntry || model('JournalEntry', JournalEntrySchema);  
export default JournalEntry;