import { model, models, Schema } from 'mongoose';  
import { UUID } from 'mongodb';
import { User } from '@/types/user';

const UserSchema = new Schema<User>(  
    {  
        id: UUID, // @todo generated by db
        clerkId: String,
        email: String, // @todo unique
        createdAt: Date, // @todo generated by db
        updatedAt: Date, // @todo generated by db
    },  
);  
const User = models.User || model('User', UserSchema);  
export default User;