import { UUID } from 'mongodb';
import { model, models, Schema } from 'mongoose';
import { JournalEntryType, Category } from '@/types/journalEntry';

const JournalEntrySchema = new Schema<JournalEntryType>(  
    {  
        id: UUID, // @todo should be generated by db - we would want to get specific entry by id ?unique?
        createdAt: Date, //@todo should be generated by db
        updatedAt: Date, //@todo should be generated by db
        userId: UUID, // @todo what is the best way to get posts for the user and specific post with id and userId ?unique?
        tittle: String,  
        content: String,  
        category: Category, // @todo fix type
        additionalCategory: Category, // @todo fix type
    },  
    {  
        timestamps: true, 
    },
);  
const JournalEntry = models.JournalEntry || model('JournalEntry', JournalEntrySchema);  
export default JournalEntry;